# Assignment 2

-----
## Name : Vishal kumar
## PRN : 8053
-----

In [11]:
import numpy as np
import pandas as pd
import os
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.compose import make_column_selector,make_column_transformer
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis,QuadraticDiscriminantAnalysis
from sklearn.svm import SVC

In [12]:
df = pd.read_csv('drug200.csv')
df.head()

   Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

## Logistic Regression

In [14]:
X,y = df.drop('Drug',axis=1),df['Drug']

In [24]:
ohe = OneHotEncoder(sparse_output=False,drop='first').set_output(transform='pandas')
ct = make_column_transformer((ohe,make_column_selector(dtype_include='object')),
                            ('passthrough',make_column_selector(dtype_include=['int64','float64'])),
                            verbose_feature_names_out=False)
ct = ct.set_output(transform='pandas')

In [27]:
X_train,X_test,y_train,y_test  = train_test_split(X,y,test_size=0.3,random_state=26,stratify=y)
lr  = LogisticRegression(max_iter=2000)
pipe = Pipeline([('OHE',ct),("LR",lr)])
pipe.fit(X_train,y_train)
y_pred = pipe.predict(X_test)
accuracy_score(y_test,y_pred)

0.9833333333333333

In [29]:
solvers=['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga']
scores = []
for s in solvers:
    lr  = LogisticRegression(max_iter=2000,solver=s)
    pipe = Pipeline([('OHE',ct),("LR",lr)])
    pipe.fit(X_train,y_train)
    y_pred = pipe.predict(X_test)
    scores.append([s,accuracy_score(y_test,y_pred)])
df_scores = pd.DataFrame(scores,columns=['solver','accuracy'])
df_scores.sort_values('accuracy',ascending=False)

C:\Users\ragha\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

            solver  accuracy
0            lbfgs  0.983333
2        newton-cg  0.983333
3  newton-cholesky  0.966667
4              sag  0.866667
5             saga  0.833333
1        liblinear  0.783333

## KNN

In [34]:
knn = KNeighborsClassifier()
scaler = StandardScaler()
pipe = Pipeline([('OHE',ct),('SCL',scaler),("KNN",knn)])
pipe.fit(X_train,y_train)
y_pred = pipe.predict(X_test)
accuracy_score(y_test,y_pred)

0.8

In [36]:
neighbors = np.arange(1,16)
scores = []
for n in neighbors:
    knn = KNeighborsClassifier(n_neighbors=n)
    pipe = Pipeline([('OHE',ct),('SCL',scaler),("KNN",knn)])
    pipe.fit(X_train,y_train)
    y_pred = pipe.predict(X_test)
    scores.append([n,accuracy_score(y_test,y_pred)])
df_scores = pd.DataFrame(scores,columns=['n_neighbors','accuracy'])
df_scores.sort_values('accuracy',ascending=False)

    n_neighbors  accuracy
0             1  0.950000
1             2  0.883333
12           13  0.883333
13           14  0.883333
14           15  0.866667
9            10  0.833333
11           12  0.833333
2             3  0.816667
3             4  0.816667
10           11  0.816667
4             5  0.800000
8             9  0.783333
5             6  0.766667
6             7  0.766667
7             8  0.766667

## Linear Discriminant

In [38]:
lda = LinearDiscriminantAnalysis()
pipe = Pipeline([('OHE',ct),('LDA',lda)])
pipe.fit(X_train,y_train)
y_pred = pipe.predict(X_test)
accuracy_score(y_test,y_pred)

0.9

In [41]:
solvers = ['svd', 'lsqr', 'eigen']
scores = []
for s in solvers:
    lda = LinearDiscriminantAnalysis(solver=s)
    pipe = Pipeline([('OHE',ct),('LDA',lda)])
    pipe.fit(X_train,y_train)
    y_pred = pipe.predict(X_test)
    scores.append([s,accuracy_score(y_test,y_pred)])
df_scores = pd.DataFrame(scores,columns=['solver','accuracy'])
df_scores.sort_values('accuracy',ascending=False)

  solver  accuracy
0    svd  0.900000
1   lsqr  0.883333
2  eigen  0.883333

## QDA

In [44]:
lda = QuadraticDiscriminantAnalysis()
pipe = Pipeline([('OHE',ct),('LDA',lda)])
pipe.fit(X_train,y_train)
y_pred = pipe.predict(X_test)
accuracy_score(y_test,y_pred)

C:\Users\ragha\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\discriminant_analysis.py:935: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

0.45

In [45]:
params = [0.1,0.3,0.5,0.7,0.9]
scores = []
for r in params:
    lda = QuadraticDiscriminantAnalysis(reg_param=r)
    pipe = Pipeline([('OHE',ct),('LDA',lda)])
    pipe.fit(X_train,y_train)
    y_pred = pipe.predict(X_test)
    scores.append([r,accuracy_score(y_test,y_pred)])
df_scores = pd.DataFrame(scores,columns=['reg param','accuracy'])
df_scores.sort_values('accuracy',ascending=False)

C:\Users\ragha\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\discriminant_analysis.py:935: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
C:\Users\ragha\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\discriminant_analysis.py:935: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
C:\Users\ragha\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\discriminant_analysis.py:935: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
C:\Users\ragha\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\discriminant_analysis.py:935: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
C:\Users\ragha\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\discriminant_analysis.py:935: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

   reg param  accuracy
0        0.1  1.000000
1        0.3  0.950000
2        0.5  0.833333
3        0.7  0.716667
4        0.9  0.700000

## SVM

In [46]:
svm = SVC()
scaler = StandardScaler()
pipe = Pipeline([('OHE',ct),('SCL',scaler),('SVM',svm)])
pipe.fit(X_train,y_train)
y_pred = pipe.predict(X_test)
accuracy_score(y_test,y_pred)

0.9333333333333333

In [55]:
kernels = ['linear', 'poly', 'rbf', 'sigmoid']
scores = []
for k in kernels:
    svm = SVC(kernel=k)
    pipe = Pipeline([('OHE',ct),('SCL',scaler),('SVM',svm)])
    pipe.fit(X_train,y_train)
    y_pred = pipe.predict(X_test)
    scores.append([k,accuracy_score(y_test,y_pred)])
df_scores = pd.DataFrame(scores,columns=['kernel','accuracy'])
df_scores.sort_values('accuracy',ascending=False)

    kernel  accuracy
0   linear  0.966667
2      rbf  0.933333
3  sigmoid  0.933333
1     poly  0.816667

### The model eith the best accuracy is QuadraticDiscriminantAnalysis(reg_param=0.1)