# Joint Probability
- when event A and B are independent of each other - $$P(A \text{ and } B) = P(A \cap B) = P(A) \times P(B)$$
- EVENT A : Patient is diabetic
- EVENT B : Patient has heart disease
- P(diabetic and hear disease oatient = P(diabetic Pateint) x P(heart disease Patient)
- Both Event are Independent

# Conditional Probability 
- When one is alredy happened and another one is about to happen P(B/A) = Probability of event B happening, Given That event A has happened
- $$P(B \mid A) = \frac{P(A \cap B)}{P(A)}$$
- $P(B \mid A)$: The conditional probability of event $B$ given event $A$.
- $P(A \cap B)$ (or joint probability): The probability that both events $A$ and $B$ happen together.
- $P(A)$: The marginal probability of event $A$ happening on its own.
- P(Patient has heart disease guven that patient has diabetic)
- First consider onlyy diabetic petients and within them look for pateints with heart disease

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [3]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [15]:
df = pd.read_csv("titanic.csv")

In [16]:
df.head()

   survived  pclass  gender   age  sibsp  parch     fare embarked deck
0         0       3    male  22.0      1      0   7.2500        S  NaN
1         1       1  female  38.0      1      0  71.2833        C    C
2         1       3  female  26.0      0      0   7.9250        S  NaN
3         1       1  female  35.0      1      0  53.1000        S    C
4         0       3    male  35.0      0      0   8.0500        S  NaN

In [17]:
df.isnull().sum()

survived      0
pclass        0
gender        0
age         177
sibsp         0
parch         0
fare          0
embarked      2
deck        688
dtype: int64

In [19]:
df = df[['gender','survived']]
df.head()

   gender  survived
0    male         0
1  female         1
2  female         1
3  female         1
4    male         0

In [20]:
df = df.dropna()

In [21]:
total = len(df)
total

891

In [22]:
# Marginal Probability of gender
total_female = len(df[df['gender']=='female'])
total_female

314

In [23]:
total_male = len(df[df['gender']=='male'])
total_male

577

In [27]:
p_female = total_female/total
p_female

0.35241301907968575

In [25]:
p_male = total_male/total
p_male

0.6475869809203143

In [28]:
# Marginal prob of Survival

total_survived = len(df[df['survived']==1])
total_survived

342

In [29]:
total_not_survived = len(df[df['survived']==0])
total_not_survived

549

In [30]:
p_survived = total_survived/total
p_survived

0.3838383838383838

In [54]:
p_not_survived = total_not_survived/total
p_not_survived

0.6161616161616161

In [55]:
print(f"P(male) : {p_male:.3f}")
print(f"P(female) : {p_female:.3f}")
print(f"P(survived=1) : {p_survived:.3f}")
print(f"P(survived=0) : {p_not_survived:.3f}")

P(male) : 0.648
P(female) : 0.352
P(survived=1) : 0.384
P(survived=0) : 0.616

# Joint probabilities

In [34]:
total_survived_male = len(df[(df['survived']==1)& (df['gender']=='male')])
total_survived_male

109

In [39]:
total_not_survived_male = len(df[(df['survived']==0)& (df['gender']=='male')])
total_not_survived_male

468

In [35]:
total_survived_female = len(df[(df['survived']==1)& (df['gender']=='female')])
total_survived_female

233

In [40]:
total_not_survived_female = len(df[(df['survived']==0)& (df['gender']=='female')])
total_not_survived_female

81

In [41]:
p_female_survived = total_survived_female/total
p_female_survived

0.2615039281705948

In [42]:
p_male_survived = total_survived_male/total
p_male_survived

0.122334455667789

In [43]:
p_female_not_survived = total_not_survived_female/total
p_female_not_survived

0.09090909090909091

In [44]:
p_male_not_survived = total_not_survived_male/total
p_male_not_survived

0.5252525252525253

In [53]:
print(f"P(female,survived=1) : {p_female_survived :.3f}")
print(f"P(female,survived=0) : {p_female_not_survived:.3f}")
print(f"P(male,survived=1) : {p_male_survived:.3f}")
print(f"P(male,survived=0) : {p_male_not_survived:.3f}")

P(female,survived=1) : 0.262
P(female,survived=0) : 0.091
P(male,survived=1) : 0.122
P(male,survived=0) : 0.525

# Conditional Probabilities

In [45]:
p_survived_given_female = p_female_survived/p_female
p_survived_given_female

0.7420382165605095

In [47]:
p_survived_given_male = p_male_survived/p_male
p_survived_given_male

0.18890814558058924

In [49]:
print(f"P(survived=1 | gender = female) : {p_survived_given_female:.3f}")

P(survived=1 | gender = female) : 0.742

In [50]:
print(f"P(survived=1 | gender = male) : {p_survived_given_male:.3f}")

P(survived=1 | gender = male) : 0.189

In [64]:
print(f"{0.01*0.9/0.10*100} %")

9.000000000000002 %