In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.metrics import root_mean_squared_error,r2_score

In [10]:
os.chdir("E:/Vishal_Adesh/Machine Learning/Datasets")

In [11]:
housing = pd.read_csv("Housing.csv")
housing.head()

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,61000.0,6360,2,1,1,yes,no,no,no,no,0,no

In [12]:
X, y = housing.drop('price',axis=1),housing['price']
# poly = PolynomialFeatures(include_bias=False)
# X_poly = poly.fit_transform(X)
# X_poly

In [13]:
# One hot Encoding categorical features

from sklearn.preprocessing import OneHotEncoder


categorical_features = ["driveway","recroom","fullbase","gashw","airco","prefarea"]

#create instance of onehot encoder
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore',drop="first").set_output(transform='pandas')
num_cols = list(X.select_dtypes(include=['number']).columns)
str_cols = list(X.select_dtypes(include=['object']).columns)
X_num = X[num_cols]
X_str = X[str_cols]
X_ohe = encoder.fit_transform(X_str)
X_enc = pd.concat([X_num,X_ohe],axis=1)

In [14]:
X.dtypes

lotsize      int64
bedrooms     int64
bathrms      int64
stories      int64
driveway    object
recroom     object
fullbase    object
gashw       object
airco       object
garagepl     int64
prefarea    object
dtype: object

In [15]:
str_cols

['driveway', 'recroom', 'fullbase', 'gashw', 'airco', 'prefarea']

In [16]:
X_enc

,lotsize,bedrooms,bathrms,stories,garagepl,driveway_yes,recroom_yes,fullbase_yes,gashw_yes,airco_yes,prefarea_yes
0,5850,3,1,2,1,1.0,0.0,1.0,0.0,0.0,0.0
1,4000,2,1,1,0,1.0,0.0,0.0,0.0,0.0,0.0
2,3060,3,1,1,0,1.0,0.0,0.0,0.0,0.0,0.0
3,6650,3,1,2,0,1.0,1.0,0.0,0.0,0.0,0.0
4,6360,2,1,1,0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
541,4800,3,2,4,0,1.0,1.0,0.0,0.0,1.0,0.0
542,6000,3,2,4,0,1.0,0.0,0.0,0.0,1.0,0.0
543,6000,3,2,4,1,1.0,1.0,0.0,0.0,1.0,0.0
544,6000,3,2,2,1,1.0,1.0,0.0,0.0,1.0,0.0
545,6000,3,1,2,1,1.0,0.0,0.0,0.0,1.0,0.0

In [17]:
# encoded_data = encoder.fit_transform(housing[categorical_features])
# encoded_data

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X_enc,y,random_state=26,test_size=0.3)

In [34]:
ridge = Ridge(alpha=0.5)
ridge.fit(X_train,y_train)

Ridge(alpha=0.5)

In [35]:
ridge.coef_

array([4.55716109e+00, 2.05292590e+03, 1.34612465e+04, 6.01158400e+03,
       3.33253522e+03, 6.36187958e+03, 3.21338971e+03, 6.71962636e+03,
       1.08160358e+04, 1.23942853e+04, 9.47811195e+03])

In [44]:
alpha = [0.1,0.25,0.7,1,1.5,2,5,10,50]

for i in alpha:
    ridge = Ridge(alpha=i)
    ridge.fit(X_train,y_train)
    y_pred = ridge.predict(X_test)
    print("\nAlpha : ",i)
    print("ridge.coef : \n",ridge.coef_)
    print("root_mean_squared_error : ",root_mean_squared_error(y_test,y_pred))

Alpha :  0.1
ridge.coef :
 [4.54998703e+00 2.04575807e+03 1.35177111e+04 5.99774899e+03
 3.32120436e+03 6.42863698e+03 3.20814015e+03 6.72513697e+03
 1.11203774e+04 1.24678646e+04 9.53342540e+03]
root_mean_squared_error :  15054.589007441034

Alpha :  0.25
ridge.coef :
 [4.55267900e+00 2.04844323e+03 1.34965079e+04 6.00301168e+03
 3.32551129e+03 6.40338671e+03 3.21012411e+03 6.72313484e+03
 1.10043049e+04 1.24400627e+04 9.51256976e+03]
root_mean_squared_error :  15057.144270758694

Alpha :  0.7
ridge.coef :
 [4.56074210e+00 2.05651793e+03 1.34331109e+04 6.01826809e+03
 3.33801974e+03 6.32917971e+03 3.21596371e+03 6.71667144e+03
 1.06699032e+04 1.23581514e+04 9.45081124e+03]
root_mean_squared_error :  15065.039848066559

Alpha :  1
ridge.coef :
 [4.56610469e+00 2.06191429e+03 1.33910373e+04 6.02801491e+03
 3.34603053e+03 6.28094679e+03 3.21975767e+03 6.71200452e+03
 1.04578147e+04 1.23047338e+04 9.41029097e+03]
root_mean_squared_error :  15070.47480878495

Alpha :  1.5
ridge.coef :
 [4.57501483e+00 2.07092525e+03 1.33212847e+04 6.04354881e+03
 3.35883365e+03 6.20264946e+03 3.22589333e+03 6.70364156e+03
 1.01221116e+04 1.22176935e+04 9.34386692e+03]
root_mean_squared_error :  15079.794114038723

Alpha :  2
ridge.coef :
 [4.58388535e+00 2.07994974e+03 1.32520276e+04 6.05824521e+03
 3.37099294e+03 6.12683340e+03 3.23178281e+03 6.69460796e+03
 9.80688260e+03 1.21329917e+04 9.27877111e+03]
root_mean_squared_error :  15089.39235292554

Alpha :  5
ridge.coef :
 [4.63604310e+00 2.13396819e+03 1.28483134e+04 6.13150469e+03
 3.43257958e+03 5.71695641e+03 3.26155618e+03 6.62939223e+03
 8.25733745e+03 1.16662830e+04 8.91295353e+03]
root_mean_squared_error :  15150.756031047047

Alpha :  10
ridge.coef :
 [4.71806398e+00 2.22121966e+03 1.22249605e+04 6.21153666e+03
 3.50364018e+03 5.16451401e+03 3.29007242e+03 6.49478922e+03
 6.52508325e+03 1.10058151e+04 8.37951174e+03]
root_mean_squared_error :  15259.10260185512

Alpha :  50
ridge.coef :
 [5.19170799e+00 2.67773133e+03 8.92726526e+03 6.16251460e+03
 3.56408629e+03 3.05411641e+03 3.04769663e+03 5.31160706e+03
 2.41345831e+03 7.90491426e+03 5.81070633e+03]
root_mean_squared_error :  16100.225467703769

In [32]:
lr = LinearRegression()
lr.fit(X_train,y_train)

LinearRegression()

In [33]:
lr.coef_

array([4.54819141e+00, 2.04397000e+03, 1.35318649e+04, 5.99418957e+03,
       3.31829347e+03, 6.44561782e+03, 3.20680765e+03, 6.72642730e+03,
       1.11990998e+04, 1.24865428e+04, 9.54740598e+03])

In [2]:
y_pred = ridge.predict(X_test)
root_mean_squared_error(y_test,y_pred)

NameError: name 'ridge' is not defined

In [25]:
poly = PolynomialFeatures(degree=2,include_bias=False).set_output(transform='pandas')
X_poly = poly.fit_transform(X_enc)

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X_poly, y, random_state=26,test_size=0.2)

In [33]:
lr = LinearRegression()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)
root_mean_squared_error(y_test,y_pred)

125089.77106543227

In [34]:
r2_score(y_test,y_pred)

-20.654671618630715

In [35]:
poly = PolynomialFeatures(degree=3,include_bias=False).set_output(transform='pandas')
X_poly = poly.fit_transform(X_enc)
X_train, X_test, y_train, y_test = train_test_split(X_poly, y, random_state=26,test_size=0.2)
lr = LinearRegression()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)
print(root_mean_squared_error(y_test,y_pred))
print(r2_score(y_test,y_pred))

79211.39581056502
-7.6832706797751396

In [36]:
poly = PolynomialFeatures(degree=4,include_bias=False).set_output(transform='pandas')
X_poly = poly.fit_transform(X_enc)
X_train, X_test, y_train, y_test = train_test_split(X_poly, y, random_state=26,test_size=0.2)
lr = LinearRegression()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)
print(root_mean_squared_error(y_test,y_pred))
print(r2_score(y_test,y_pred))

125089.77106543227
-20.654671618630715

In [37]:
pizza = pd.read_csv("pizza.csv")
pizza.head()

   Promote  Sales
0       23    554
1       56   1339
2       34    815
3       25    609
4       67   1600

In [49]:
X = pizza['Promote'].values
y = pizza['Sales'].values
X_bar = np.mean(X)
y_bar = np.mean(y)
n = len(pizza)

"E:\Vishal_Adesh\Machine Learning\Day2\image.png"

In [ ]:
# $$b_1 = \frac{\text{Cov}(X, y)}{\text{Var}(X)}$$

b1 = (((np.sum(X*y)/n) - X_bar*y_bar) / (((np.sum(X**2)/n) - X_bar**2)))

In [55]:
b1

23.506403021550746

In [56]:
b0 = y_bar - b1*X_bar
b0

5.485865363253652

In [ ]:
m