In [1]:
import pandas as pd
from scipy import stats

In [2]:
df = pd.read_csv("tips.csv")
df.head()

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3.560330e+15,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4.478070e+15,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6.011810e+15,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4.676140e+15,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4.832730e+15,Sun2251

In [11]:
male_tips = df[df['gender'] == 'Male']['tip']
female_tips = df[df['gender'] == 'Female']['tip']

In [12]:
male_tips

1      1.66
2      3.50
3      3.31
5      4.71
6      2.00
       ...
236    1.00
237    1.17
239    5.92
241    2.00
242    1.75
Name: tip, Length: 157, dtype: float64

In [13]:
female_tips

0      1.01
4      3.61
11     5.00
14     3.02
16     1.67
       ...
226    2.00
229    2.88
238    4.67
240    2.00
243    3.00
Name: tip, Length: 87, dtype: float64

In [14]:
print("Male Mean tip : ", male_tips.mean())
print("Feale Mean tip : ", female_tips.mean())

Male Mean tip :  3.0896178343949043
Feale Mean tip :  2.8334482758620685

### Two-sample t-test

In [15]:
t_statistic, p_value = stats.ttest_ind(male_tips,female_tips)
print("T-statistic:",t_statistic)
print("P_value (one-tailed) : ", p_value)

T-statistic: 1.387859705421269
P_value (one-tailed) :  0.16645623503456755

In [16]:
alpha = 0.05

if p_value < alpha :
    print("There is significant difference in spending score between Male and Female Group.")
else:
    print("There is no significant difference in spending score between Male and Female Group.")

There is no significant difference in spending score between Male and Female Group.

## Ex: is there a statistically significant diff in the average runs runs scored by sachin tendulkar when playing against australia vs pakistan

In [17]:
df = pd.read_csv("Sachin_Tendulkar (1).csv")
df.head()

,Match_No,Innings,match_date,Versus,mode_of_dismissal,Runs,Balls_faced
0,1,1,1989-12-18 00:00:00,Pakistan,c Wasim Akram b Waqar Younis,0,2
1,2,2,1990-03-01 00:00:00,New Zealand,c & b S A Thomson,0,2
2,3,3,1990-03-06 00:00:00,New Zealand,c †I D S Smith b S A Thomson,36,39
3,4,4,1990-04-25 00:00:00,Sri Lanka,run out,10,12
4,5,5,1990-04-27 00:00:00,Pakistan,c Saeed Anwar b Imran Khan,20,25

In [23]:
df["Versus"].unique()

array(['Pakistan', 'New Zealand', 'Sri Lanka', 'England', 'West Indies',
       'South Africa', 'Australia', 'Zimbabwe', 'United Arab Emirates',
       'Bangladesh', 'Kenya', 'Netherlands', 'Namibia', 'Bermuda',
       'Ireland'], dtype=object)

In [24]:
against_pakistan = df[df["Versus"] == "Pakistan"]["Runs"]
against_australia = df[df["Versus"] == "Australia"]["Runs"]

In [25]:
against_pakistan

0       0
4      20
12     52
15     49
16      0
       ..
395    97
396    30
418     8
440    85
451    52
Name: Runs, Length: 67, dtype: int64

In [26]:
against_australia

21     36
22     57
24     21
26     31
28      4
       ..
424    10
439    53
442     2
445     3
447    14
Name: Runs, Length: 70, dtype: int64

In [32]:
print("Pakistan Mean Runs : ", against_pakistan.mean())
print("Australia Mean Runs : ", against_australia.mean())

Pakistan Mean Runs :  37.701492537313435
Australia Mean Runs :  43.957142857142856

In [33]:
t_statistic, p_value = stats.ttest_ind(against_pakistan,against_australia)
print("T-statistic:",t_statistic)
print("P_value  : ", p_value)

T-statistic: -0.8981577479648452
P_value  :  0.3707005236898371

In [34]:
alpha = 0.05
if p_value < alpha :
    print("There is significant difference in the average runs runs scored by sachin tendulkar when playing against australia vs pakistan")
else:
    print("There is no significant difference in the average runs runs scored by sachin tendulkar when playing against australia vs pakistan")

There is no significant difference in the average runs runs scored by sachin tendulkar when playing against australia vs pakistan