In [2]:
from scipy.stats import f_oneway
import pandas as pd

In [3]:
df = pd.read_csv("StudentsPerformance.csv")
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [4]:
df["parental level of education"].unique()

array(["bachelor's degree", 'some college', "master's degree",
       "associate's degree", 'high school', 'some high school'],
      dtype=object)

In [7]:
g1 = df["math score"][df["parental level of education"] == "some high school"]

g2 = df["math score"][df["parental level of education"] == "high school"]

g3 = df["math score"][df["parental level of education"] == "some college"]

g4 = df["math score"][df["parental level of education"] == "associate's degree"]

g5 = df["math score"][df["parental level of education"] == "bachelor's degree"]

g6 = df["math score"][df["parental level of education"] == "master's degree"]

In [10]:
fstat, pval = f_oneway(g1, g2, g3, g4, g5, g6)
print("fstat : ",fstat)
print("pval : ",pval)
alpha = 0.05

if pval < alpha:
    print("Reject H0")
else:
    print("Do not reject H0")

fstat :  6.521582600453217
pval :  5.592272384107223e-06
Reject H0

## Exercise
### Is there a statistically siginificant differnece between how people tip,whose total bill amounts are <5,5-10,10-15,>15 in the tips dataset(Handel boundary conditions approprriately)

In [12]:
df = pd.read_csv("tips.csv")
df.head()

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3.560330e+15,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4.478070e+15,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6.011810e+15,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4.676140e+15,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4.832730e+15,Sun2251

In [15]:
g1 = df["tip"][df["total_bill"] < 5]

g2 = df["tip"][(df["total_bill"] >= 5) & (df["total_bill"] <= 10)]

g3 = df["tip"][(df["total_bill"] > 10) & (df["total_bill"] <= 15)]

g4 = df["tip"][df["total_bill"] > 15]

In [16]:
fstat, pval = f_oneway(g1, g2, g3, g4)
print("fstat : ",fstat)
print("pval : ",pval)
alpha = 0.05

if pval < alpha:
    print("Reject H0")
else:
    print("Do not reject H0")

fstat :  24.390512702059862
pval :  8.221013856103298e-14
Reject H0

In [17]:
# test 2

g1 = df["tip"][df["total_bill"] < 13]

g2 = df["tip"][(df["total_bill"] >= 13) & (df["total_bill"] <= 17)]

g3 = df["tip"][(df["total_bill"] > 17) & (df["total_bill"] <= 22)]

g4 = df["tip"][df["total_bill"] > 22]

In [19]:
fstat, pval = f_oneway(g1, g2, g3, g4)
print("fstat : ",fstat)
print("pval : ",pval)
alpha = 0.05

if pval < alpha:
    print("Reject H0")
else:
    print("Do not reject H0")

fstat :  47.468466815824726
pval :  4.0212491169443505e-24
Reject H0