In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
from sklearn.linear_model import LinearRegression, Ridge, ElasticNet, Lasso
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.metrics import root_mean_squared_error,r2_score

In [3]:
os.chdir("E:/Vishal_Adesh/Machine Learning/Datasets")

In [4]:
housing = pd.read_csv("Housing.csv")
housing.head()

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,61000.0,6360,2,1,1,yes,no,no,no,no,0,no

In [5]:
X, y = housing.drop('price',axis=1),housing['price']
# poly = PolynomialFeatures(include_bias=False)
# X_poly = poly.fit_transform(X)
# X_poly

In [6]:
# One hot Encoding categorical features

from sklearn.preprocessing import OneHotEncoder


categorical_features = ["driveway","recroom","fullbase","gashw","airco","prefarea"]

#create instance of onehot encoder
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore',drop="first").set_output(transform='pandas')
num_cols = list(X.select_dtypes(include=['number']).columns)
str_cols = list(X.select_dtypes(include=['object']).columns)
X_num = X[num_cols]
X_str = X[str_cols]
X_ohe = encoder.fit_transform(X_str)
X_enc = pd.concat([X_num,X_ohe],axis=1)

In [7]:
X.dtypes

lotsize      int64
bedrooms     int64
bathrms      int64
stories      int64
driveway    object
recroom     object
fullbase    object
gashw       object
airco       object
garagepl     int64
prefarea    object
dtype: object

In [8]:
str_cols

['driveway', 'recroom', 'fullbase', 'gashw', 'airco', 'prefarea']

In [9]:
X_enc

,lotsize,bedrooms,bathrms,stories,garagepl,driveway_yes,recroom_yes,fullbase_yes,gashw_yes,airco_yes,prefarea_yes
0,5850,3,1,2,1,1.0,0.0,1.0,0.0,0.0,0.0
1,4000,2,1,1,0,1.0,0.0,0.0,0.0,0.0,0.0
2,3060,3,1,1,0,1.0,0.0,0.0,0.0,0.0,0.0
3,6650,3,1,2,0,1.0,1.0,0.0,0.0,0.0,0.0
4,6360,2,1,1,0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
541,4800,3,2,4,0,1.0,1.0,0.0,0.0,1.0,0.0
542,6000,3,2,4,0,1.0,0.0,0.0,0.0,1.0,0.0
543,6000,3,2,4,1,1.0,1.0,0.0,0.0,1.0,0.0
544,6000,3,2,2,1,1.0,1.0,0.0,0.0,1.0,0.0
545,6000,3,1,2,1,1.0,0.0,0.0,0.0,1.0,0.0

In [10]:
# encoded_data = encoder.fit_transform(housing[categorical_features])
# encoded_data

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X_enc,y,random_state=26,test_size=0.3)

In [12]:
lasso = Lasso(alpha=0.5)
lasso.fit(X_train,y_train)

Lasso(alpha=0.5)

In [13]:
lasso.coef_

array([4.54869526e+00, 2.04316888e+03, 1.35306109e+04, 5.99462478e+03,
       3.31832427e+03, 6.44075108e+03, 3.20462441e+03, 6.72611906e+03,
       1.11856907e+04, 1.24841035e+04, 9.54524785e+03])

In [14]:
alpha = [0.1,0.25,0.7,1,1.5,2,5,10,50]

for i in alpha:
    lasso = Lasso(alpha=i)
    lasso.fit(X_train,y_train)
    y_pred = lasso.predict(X_test)
    print("\nAlpha : ",i)
    print("lasso.coef : \n",lasso.coef_)
    print("root_mean_squared_error : ",root_mean_squared_error(y_test,y_pred))

Alpha :  0.1
lasso.coef :
 [4.54829218e+00 2.04381009e+03 1.35316144e+04 5.99427629e+03
 3.31829959e+03 6.44464452e+03 3.20637126e+03 6.72636525e+03
 1.11964182e+04 1.24860549e+04 9.54697445e+03]
root_mean_squared_error :  15052.992873959423

Alpha :  0.25
lasso.coef :
 [4.54844334e+00 2.04356963e+03 1.35312380e+04 5.99440698e+03
 3.31830885e+03 6.44318448e+03 3.20571619e+03 6.72627293e+03
 1.11923954e+04 1.24853231e+04 9.54632698e+03]
root_mean_squared_error :  15053.119189953894

Alpha :  0.7
lasso.coef :
 [4.54889680e+00 2.04284827e+03 1.35301091e+04 5.99479902e+03
 3.31833661e+03 6.43880436e+03 3.20375098e+03 6.72599596e+03
 1.11803269e+04 1.24831278e+04 9.54438455e+03]
root_mean_squared_error :  15053.49875508817

Alpha :  1
lasso.coef :
 [4.54919911e+00 2.04236736e+03 1.35293565e+04 5.99506038e+03
 3.31835512e+03 6.43588427e+03 3.20244084e+03 6.72581131e+03
 1.11722813e+04 1.24816643e+04 9.54308960e+03]
root_mean_squared_error :  15053.752312777462

Alpha :  1.5
lasso.coef :
 [4.54970296e+00 2.04156585e+03 1.35281021e+04 5.99549599e+03
 3.31838597e+03 6.43101747e+03 3.20025728e+03 6.72550357e+03
 1.11588719e+04 1.24792250e+04 9.54093135e+03]
root_mean_squared_error :  15054.175823113572

Alpha :  2
lasso.coef :
 [4.55020681e+00 2.04076434e+03 1.35268477e+04 5.99593159e+03
 3.31841682e+03 6.42615067e+03 3.19807372e+03 6.72519582e+03
 1.11454625e+04 1.24767858e+04 9.53877310e+03]
root_mean_squared_error :  15054.60047610018

Alpha :  5
lasso.coef :
 [4.55322991e+00 2.03595526e+03 1.35193214e+04 5.99854522e+03
 3.31860191e+03 6.39694985e+03 3.18497235e+03 6.72334936e+03
 1.10650062e+04 1.24621502e+04 9.52582361e+03]
root_mean_squared_error :  15057.172384248272

Alpha :  10
lasso.coef :
 [4.55826840e+00 2.02794014e+03 1.35067777e+04 6.00290128e+03
 3.31891040e+03 6.34828182e+03 3.16313672e+03 6.72027192e+03
 1.09309124e+04 1.24377577e+04 9.50424112e+03]
root_mean_squared_error :  15061.55024469272

Alpha :  50
lasso.coef :
 [4.59857637e+00 1.96381914e+03 1.34064274e+04 6.03774968e+03
 3.32137832e+03 5.95893758e+03 2.98845174e+03 6.69565238e+03
 9.85816205e+03 1.22426176e+04 9.33158120e+03]
root_mean_squared_error :  15100.671744676278

In [15]:
lr = LinearRegression()
lr.fit(X_train,y_train)

LinearRegression()

In [16]:
lr.coef_

array([4.54819141e+00, 2.04397000e+03, 1.35318649e+04, 5.99418957e+03,
       3.31829347e+03, 6.44561782e+03, 3.20680765e+03, 6.72642730e+03,
       1.11990998e+04, 1.24865428e+04, 9.54740598e+03])

In [17]:
y_pred = lasso.predict(X_test)
root_mean_squared_error(y_test,y_pred)

15100.671744676278

In [18]:
poly = PolynomialFeatures(degree=2,include_bias=False).set_output(transform='pandas')
X_poly = poly.fit_transform(X_enc)

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X_poly, y, random_state=26,test_size=0.2)

In [20]:
lr = LinearRegression()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)
root_mean_squared_error(y_test,y_pred)

15262.951267269256

In [21]:
r2_score(y_test,y_pred)

0.6776074168356645

In [22]:
poly = PolynomialFeatures(degree=3,include_bias=False).set_output(transform='pandas')
X_poly = poly.fit_transform(X_enc)
X_train, X_test, y_train, y_test = train_test_split(X_poly, y, random_state=26,test_size=0.2)
lr = LinearRegression()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)
print(root_mean_squared_error(y_test,y_pred))
print(r2_score(y_test,y_pred))

79211.39581056502
-7.6832706797751396

In [23]:
poly = PolynomialFeatures(degree=4,include_bias=False).set_output(transform='pandas')
X_poly = poly.fit_transform(X_enc)
X_train, X_test, y_train, y_test = train_test_split(X_poly, y, random_state=26,test_size=0.2)
lr = LinearRegression()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)
print(root_mean_squared_error(y_test,y_pred))
print(r2_score(y_test,y_pred))

125089.77106543227
-20.654671618630715

# Elastic Net

In [25]:
alphas = [0.1,0.25,0.7,1,1.5,2,5,10,50]
ratios = [0.1,0.25,0.5,0.75,1]
scores = []
for a in alphas:
    for r in ratios:
        el = ElasticNet(alpha=a,l1_ratio=r)
        el.fit(X_train,y_train)
        y_pred = el.predict(X_test)
        scores.append([a,r,root_mean_squared_error(y_test,y_pred)])
df_scores = pd.DataFrame(scores, columns=['alpha','l1','score'])        
df_scores.sort_values('score')

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.804e+10, tolerance: 3.090e+07
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.786e+10, tolerance: 3.090e+07
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.746e+10, tolerance: 3.090e+07
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.679e+10, tolerance: 3.090e+07
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.214e+10, tolerance: 3.090e+07
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.886e+10, tolerance: 3.090e+07
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.871e+10, tolerance: 3.090e+07
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.836e+10, tolerance: 3.090e+07
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.769e+10, tolerance: 3.090e+07
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.233e+10, tolerance: 3.090e+07
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.956e+10, tolerance: 3.090e+07
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.945e+10, tolerance: 3.090e+07
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.919e+10, tolerance: 3.090e+07
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.867e+10, tolerance: 3.090e+07
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.278e+10, tolerance: 3.090e+07
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.975e+10, tolerance: 3.090e+07
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.966e+10, tolerance: 3.090e+07
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.943e+10, tolerance: 3.090e+07
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.896e+10, tolerance: 3.090e+07
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.303e+10, tolerance: 3.090e+07
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.993e+10, tolerance: 3.090e+07
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.986e+10, tolerance: 3.090e+07
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.967e+10, tolerance: 3.090e+07
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.925e+10, tolerance: 3.090e+07
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.337e+10, tolerance: 3.090e+07
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.004e+10, tolerance: 3.090e+07
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.998e+10, tolerance: 3.090e+07
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.981e+10, tolerance: 3.090e+07
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.944e+10, tolerance: 3.090e+07
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.365e+10, tolerance: 3.090e+07
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.029e+10, tolerance: 3.090e+07
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.025e+10, tolerance: 3.090e+07
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.015e+10, tolerance: 3.090e+07
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.993e+10, tolerance: 3.090e+07
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.477e+10, tolerance: 3.090e+07
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.043e+10, tolerance: 3.090e+07
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.040e+10, tolerance: 3.090e+07
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.033e+10, tolerance: 3.090e+07
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.018e+10, tolerance: 3.090e+07
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.585e+10, tolerance: 3.090e+07
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.059e+10, tolerance: 3.090e+07
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.059e+10, tolerance: 3.090e+07
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.057e+10, tolerance: 3.090e+07
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.052e+10, tolerance: 3.090e+07
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.845e+10, tolerance: 3.090e+07
  model = cd_fast.enet_coordinate_descent(

    alpha    l1         score
39  10.00  1.00  29841.385708
34   5.00  1.00  30246.816620
29   2.00  1.00  30727.565109
24   1.50  1.00  31296.154750
44  50.00  1.00  31770.467562
19   1.00  1.00  31903.173900
14   0.70  1.00  32338.291605
2    0.10  0.50  32524.132387
8    0.25  0.75  32546.501689
7    0.25  0.50  32552.635194
3    0.10  0.75  32573.297840
1    0.10  0.25  32579.245639
0    0.10  0.10  32580.012081
13   0.70  0.75  32670.735258
6    0.25  0.25  32707.352216
5    0.25  0.10  32790.973597
18   1.00  0.75  32835.639187
40  50.00  0.10  32912.755214
41  50.00  0.25  32976.210321
12   0.70  0.50  33007.432770
23   1.50  0.75  33051.417147
42  50.00  0.50  33115.876907
9    0.25  1.00  33158.545481
17   1.00  0.50  33203.023878
28   2.00  0.75  33211.576526
11   0.70  0.25  33220.772101
10   0.70  0.10  33278.408720
16   1.00  0.25  33311.727678
22   1.50  0.50  33314.200112
43  50.00  0.75  33317.604972
15   1.00  0.10  33325.466928
21   1.50  0.25  33328.977988
27   2.00  0.50  33330.614667
33   5.00  0.75  33332.892182
20   1.50  0.10  33336.086111
26   2.00  0.25  33349.068650
25   2.00  0.10  33383.190037
35  10.00  0.10  33450.054657
38  10.00  0.75  33454.346139
4    0.10  1.00  33457.739795
32   5.00  0.50  33458.375916
36  10.00  0.25  33475.381045
37  10.00  0.50  33501.564087
31   5.00  0.25  33504.215867
30   5.00  0.10  33506.475927