In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.metrics import root_mean_squared_error,r2_score

In [3]:
os.chdir("E:/Vishal_Adesh/Machine Learning/Datasets")

In [4]:
pizza = pd.read_csv("pizza.csv")
pizza.head()

   Promote  Sales
0       23    554
1       56   1339
2       34    815
3       25    609
4       67   1600

In [5]:
X = pizza[["Promote"]]
y = pizza["Sales"]
poly = PolynomialFeatures(include_bias=False)
X_poly = poly.fit_transform(X)
X_poly

array([[2.300e+01, 5.290e+02],
       [5.600e+01, 3.136e+03],
       [3.400e+01, 1.156e+03],
       [2.500e+01, 6.250e+02],
       [6.700e+01, 4.489e+03],
       [8.200e+01, 6.724e+03],
       [4.600e+01, 2.116e+03],
       [1.400e+01, 1.960e+02],
       [6.000e+00, 3.600e+01],
       [4.700e+01, 2.209e+03],
       [5.200e+01, 2.704e+03],
       [8.800e+01, 7.744e+03],
       [7.100e+01, 5.041e+03],
       [7.800e+01, 6.084e+03],
       [6.600e+01, 4.356e+03],
       [4.400e+01, 1.936e+03],
       [6.800e+01, 4.624e+03],
       [9.000e+01, 8.100e+03],
       [2.200e+01, 4.840e+02]])

In [6]:
lr = LinearRegression()
lr.fit(X_poly,y)

LinearRegression()

In [7]:
X = pizza[["Promote"]]
y = pizza["Sales"]
poly = PolynomialFeatures(degree=3, include_bias=False).set_output(transform="pandas")
X_poly = poly.fit_transform(X)
X_poly

    Promote  Promote^2  Promote^3
0      23.0      529.0    12167.0
1      56.0     3136.0   175616.0
2      34.0     1156.0    39304.0
3      25.0      625.0    15625.0
4      67.0     4489.0   300763.0
5      82.0     6724.0   551368.0
6      46.0     2116.0    97336.0
7      14.0      196.0     2744.0
8       6.0       36.0      216.0
9      47.0     2209.0   103823.0
10     52.0     2704.0   140608.0
11     88.0     7744.0   681472.0
12     71.0     5041.0   357911.0
13     78.0     6084.0   474552.0
14     66.0     4356.0   287496.0
15     44.0     1936.0    85184.0
16     68.0     4624.0   314432.0
17     90.0     8100.0   729000.0
18     22.0      484.0    10648.0

In [10]:
# Boston : y=medv, try rmse degree : 2,3,4,5

boston = pd.read_csv("Boston.csv")
boston.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [13]:
X = boston.drop("medv",axis=1)
y = boston["medv"]
poly = PolynomialFeatures(degree=2, include_bias=False).set_output(transform="pandas")
X_poly = poly.fit_transform(X)
X_poly

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,...,tax^2,tax ptratio,tax black,tax lstat,ptratio^2,ptratio black,ptratio lstat,black^2,black lstat,lstat^2
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,...,87616.0,4528.8,117482.40,1474.08,234.09,6072.570,76.194,157529.6100,1976.5620,24.8004
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,...,58564.0,4307.6,96049.80,2211.88,316.84,7064.820,162.692,157529.6100,3627.6660,83.5396
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,...,58564.0,4307.6,95064.86,975.26,316.84,6992.374,71.734,154315.4089,1583.1049,16.2409
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,...,49284.0,4151.4,87607.86,652.68,349.69,7379.581,54.978,155732.8369,1160.2122,8.6436
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,...,49284.0,4151.4,88111.80,1183.26,349.69,7422.030,99.671,157529.6100,2115.4770,28.4089
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,...,74529.0,5733.0,107013.27,2639.91,441.00,8231.790,203.070,153656.1601,3790.5433,93.5089
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,...,74529.0,5733.0,108353.70,2478.84,441.00,8334.900,190.680,157529.6100,3603.8520,82.4464
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,...,74529.0,5733.0,108353.70,1539.72,441.00,8334.900,118.440,157529.6100,2238.5160,31.8096
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,...,74529.0,5733.0,107411.85,1769.04,441.00,8262.450,136.080,154802.9025,2549.5560,41.9904
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,...,74529.0,5733.0,108353.70,2151.24,441.00,8334.900,165.480,157529.6100,3127.5720,62.0944

In [14]:
X = boston.drop("medv",axis=1)
y = boston["medv"]
poly = PolynomialFeatures(degree=3, include_bias=False).set_output(transform="pandas")
X_poly = poly.fit_transform(X)
X_poly

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,...,ptratio^3,ptratio^2 black,ptratio^2 lstat,ptratio black^2,ptratio black lstat,ptratio lstat^2,black^3,black^2 lstat,black lstat^2,lstat^3
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,...,3581.577,92910.3210,1165.7682,2.410203e+06,30241.39860,379.44612,6.252350e+07,7.844975e+05,9843.278760,123.505992
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,...,5639.752,125753.7960,2895.9176,2.804027e+06,64572.45480,1487.00488,6.252350e+07,1.439821e+06,33156.867240,763.551944
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,...,5639.752,124464.2572,1276.8652,2.746814e+06,28179.26722,289.08802,6.061972e+07,6.218911e+05,6379.912747,65.450827
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,...,6539.203,137998.1647,1028.0886,2.912204e+06,21695.96814,161.63532,6.145685e+07,4.578545e+05,3411.023868,25.412184
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,...,6539.203,138791.9610,1863.8477,2.945804e+06,39559.41990,531.24643,6.252350e+07,8.396328e+05,11275.492410,151.419437
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,...,9261.000,172867.5900,4264.4700,3.226779e+06,79601.40930,1963.68690,6.023168e+07,1.485855e+06,36654.553711,904.231063
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,...,9261.000,175032.9000,4004.2800,3.308122e+06,75680.89200,1731.37440,6.252350e+07,1.430369e+06,32722.976160,748.613312
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,...,9261.000,175032.9000,2487.2400,3.308122e+06,47008.83600,668.00160,6.252350e+07,8.884670e+05,12625.230240,179.406144
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,...,9261.000,173511.4500,2857.6800,3.250861e+06,53540.67600,881.79840,6.090720e+07,1.003123e+06,16521.122880,272.097792
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,...,9261.000,175032.9000,3475.0800,3.308122e+06,65679.01200,1303.98240,6.252350e+07,1.241333e+06,24645.267360,489.303872

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,...,ptratio black^3 lstat,ptratio black^2 lstat^2,ptratio black lstat^3,ptratio lstat^4,black^5,black^4 lstat,black^3 lstat^2,black^2 lstat^3,black lstat^4,lstat^5
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,...,4.763916e+09,5.977400e+07,7.499988e+05,9410.415554,9.849303e+12,1.235816e+11,1.550608e+09,1.945585e+07,2.441173e+05,3062.998004
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,...,1.017207e+10,2.342473e+08,5.394357e+06,124223.792873,9.849303e+12,2.268144e+11,5.223188e+09,1.202820e+08,2.769911e+06,63786.823981
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,...,4.348495e+09,4.461074e+07,4.576567e+05,4695.049624,9.354557e+12,9.596738e+10,9.845188e+08,1.010007e+07,1.036155e+05,1062.980336
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,...,3.378775e+09,2.517193e+07,1.875313e+05,1397.111052,9.570850e+12,7.130299e+10,5.312084e+08,3.957512e+06,2.948353e+04,219.652754
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,...,6.231780e+09,8.368704e+07,1.123840e+06,15092.126705,9.849303e+12,1.322670e+11,1.776224e+09,2.385304e+07,3.203243e+05,4301.659644
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,...,1.223125e+10,3.017326e+08,7.443440e+06,183622.201963,9.254968e+12,2.283108e+11,5.632198e+09,1.389407e+08,3.427527e+06,84553.652047
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,...,1.192198e+10,2.727427e+08,6.239617e+06,142745.586332,9.849303e+12,2.253254e+11,5.154838e+09,1.179288e+08,2.697892e+06,61720.472566
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,...,7.405284e+09,1.052300e+08,1.495332e+06,21248.863695,9.849303e+12,1.399599e+11,1.988848e+09,2.826178e+07,4.016035e+05,5706.837678
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,...,8.288252e+09,1.365050e+08,2.248194e+06,37027.067535,9.428612e+12,1.552863e+11,2.557518e+09,4.212153e+07,6.937286e+05,11425.495125
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,...,1.034639e+10,2.054158e+08,4.078299e+06,80970.004739,9.849303e+12,1.955468e+11,3.882359e+09,7.707985e+07,1.530333e+06,30383.030350

In [39]:
poly = PolynomialFeatures(degree=2, include_bias=False).set_output(transform="pandas")
X,y = boston.drop("medv", axis=1), boston["medv"]
X_poly = poly.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X_poly,y,random_state=26,test_size=0.3)

lr = LinearRegression()
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)
root_mean_squared_error(y_test,y_pred)

5.174612285813405

In [36]:
poly = PolynomialFeatures(degree=3, include_bias=False).set_output(transform="pandas")
X,y = boston.drop("medv", axis=1), boston["medv"]
X_poly = poly.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X_poly,y,random_state=26,test_size=0.3)

lr = LinearRegression()
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)
root_mean_squared_error(y_test,y_pred)

1009.1586157845794

In [37]:
poly = PolynomialFeatures(degree=4, include_bias=False).set_output(transform="pandas")
X,y = boston.drop("medv", axis=1), boston["medv"]
X_poly = poly.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X_poly,y,random_state=26,test_size=0.3)

lr = LinearRegression()
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)
root_mean_squared_error(y_test,y_pred)

72.38890265317438

In [38]:
poly = PolynomialFeatures(degree=5, include_bias=False).set_output(transform="pandas")
X,y = boston.drop("medv", axis=1), boston["medv"]
X_poly = poly.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X_poly,y,random_state=26,test_size=0.3)

lr = LinearRegression()
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)
root_mean_squared_error(y_test,y_pred)

208.4976039320933