In [1]:
import pandas as pd
from scipy import stats

In [2]:
df = pd.read_csv("tips.csv")
df.head()

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3.560330e+15,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4.478070e+15,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6.011810e+15,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4.676140e+15,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4.832730e+15,Sun2251

In [12]:
our_column = df["tip"]
our_column= our_column.sample(n=30, replace=False)

meu = 3

t_statistic, p_value = stats.ttest_1samp(our_column,meu)
print(p_value)

0.529744791012911

In [13]:
print("P-value : ", p_value)
alpha =0.5
if p_value < alpha:
    print("Reject H0")
else:
    print("Fails to Reject H0")

P-value :  0.529744791012911
Fails to Reject H0

## One Tailed One Sample T-Test

In [5]:
our_col = df["tip"].sample(n=30,replace=False)

In [7]:
meu = 3
result = stats.ttest_1samp(our_col, meu, alternative='greater') # Greater means H0 <= and H1 is > (no need to define meu < or >
print("T-statistic:",result.statistic)
print("P_value (one-tailed) : ", result.pvalue)

T-statistic: -0.2009744221978936
P_value (one-tailed) :  0.5789392422264543

In [8]:
alpha = 0.05
if result.pvalue < alpha:
    print("Reject H0 (means is significantly greater than meu")
else:
    print("Do not reject H0")

Do not reject H0

## Ex: Use Loan datset. run 2 tailed and one tailed one sample t-test
## 2-tailed -> h0: Avg income = 50 , H1 : Average income <> 50
## 1 tailed -> H0: Avg income >= 50, H1 : Avg income <50

In [9]:
df = pd.read_csv("loan.csv")
df.head()

   age  ed  employ  address  income  debtinc   creddebt   othdebt  default
0   41   3      17       12     176      9.3  11.359392  5.008608      1.0
1   27   1      10        6      31     17.3   1.362202  4.000798      0.0
2   40   1      15       14      55      5.5   0.856075  2.168925      0.0
3   41   1      15       14     120      2.9   2.658720  0.821280      0.0
4   24   2       2        0      28     17.3   1.787436  3.056564      1.0

### 2 tailed

In [17]:
our_col = df["income"].sample(n=30,replace=False)
meu = 50

result = stats.ttest_1samp(our_col, meu, alternative="two-sided") # less means H0 >= and H1 is <
print("T-statistic:",result.statistic)
print("P_value (one-tailed) : ", result.pvalue)

alpha = 0.05
if result.pvalue < alpha:
    print("Reject H0 (means is significantly greater than meu")
else:
    print("Do not reject H0")

T-statistic: -1.2359369496620742
P_value (one-tailed) :  0.22639996792149816
Do not reject H0

### one tailed

In [42]:
our_col = df["income"].sample(n=30,replace=False)
meu = 50

In [43]:
result = stats.ttest_1samp(our_col, meu, alternative='less') # less means H0 >= and H1 is <
print("T-statistic:",result.statistic)
print("P_value (one-tailed) : ", result.pvalue)

T-statistic: -3.8785138121778866
P_value (one-tailed) :  0.0002779238251257336

In [44]:
alpha = 0.05
if result.pvalue < alpha:
    print("Reject H0 (means is significantly greater than meu")
else:
    print("Do not reject H0")

Reject H0 (means is significantly greater than meu