In [1]:
from scipy.stats import f_oneway
from pandas import read_csv

In [2]:
df = read_csv("../Files/studentsPerformance.csv")

In [3]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [ ]:
q1 = df["math score"][df["parental level of education"] == "some high school"]
q2 = df["math score"][df["parental level of education"] == "high school"]
q3 = df["math score"][df["parental level of education"] == "some college"]
q4 = df["math score"][df["parental level of education"] == "associate\'s degree"]
q5 = df["math score"][df["parental level of education"] == "Bachelor\'s degree"]
q6 = df["math score"][df["parental level of education"] == "master\'s degree"]

In [9]:
q3

1      69
4      76
6      88
7      40
13     78
       ..
976    60
983    78
989    67
998    68
999    77
Name: math score, Length: 226, dtype: int64

In [10]:
fstat,pval = f_oneway(q1,q2,q3,q4,q5,q6)

In [11]:
alpha = 0.05
if pval < alpha:
    print("Reject H0")
else:
    print("Do not reject H0")

Reject H0

### Exercise : is there a statistically significant difference between how people tip, whose total bill amounts are < $5 , $5-10, $10-15 , >$15 in the tips dataset ?

In [20]:
df = read_csv("../Files/tips.csv")
df

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3.560330e+15,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4.478070e+15,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6.011810e+15,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4.676140e+15,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4.832730e+15,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5.296070e+15,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3.506810e+15,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6.011890e+15,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4.375220e+12,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3.511450e+15,Thur672

In [21]:
q1 = df["tip"][df["total_bill"] < 5]
q2 = df["tip"][(df["total_bill"] >= 5) & (df["total_bill"] < 10)]
q3 = df["tip"][(df["total_bill"] >= 10) & (df["total_bill"] <= 15)]
q4 = df["tip"][df["total_bill"] > 15]

In [22]:
fstat,pval = f_oneway(q1,q2,q3,q4)
print(f"fstat : {fstat}")
print(f"pvalue : {pval}")

fstat : 24.390512702059862
pvalue : 8.221013856103342e-14

In [23]:
alpha = 0.05
if pval < alpha:
    print("Reject H0")
else:
    print("Do not reject H0")

Reject H0