In [1]:
import pandas as pd
from scipy import stats

In [2]:

df = pd.read_csv("../Files/cust_seg.csv")
df

,custid,sex,AqChannel,region,Marital_status,segment,pre_usage,Post_usage_1month,Latest_mon_usage,post_usage_2ndmonth
0,70,0,4,1,1,1,57,52,49.2,57.2
1,121,1,4,2,1,3,68,59,63.6,64.9
2,86,0,4,3,1,1,44,33,64.8,36.3
3,141,0,4,3,1,3,63,44,56.4,48.4
4,172,0,4,2,1,2,47,52,68.4,57.2
...,...,...,...,...,...,...,...,...,...,...
195,31,1,2,2,2,1,55,59,62.4,64.9
196,145,1,4,2,1,3,42,46,45.6,50.6
197,187,1,4,2,2,1,57,41,68.4,45.1
198,118,1,4,2,1,1,55,62,69.6,68.2
199,137,1,4,3,1,2,63,65,78.0,71.5

In [3]:
usage_data = df[["pre_usage","Post_usage_1month"]]
usage_data = usage_data.sample(n=30)

In [6]:
tstat, pval = stats.ttest_rel(usage_data["pre_usage"],usage_data["Post_usage_1month"])
print(f"tstat : {tstat}")
print(f"pval : {pval}")

tstat : -0.4645631615330367
pval : 0.6457133884050847

In [7]:
alpha = 0.05
if pval < alpha:
    print(f"Reject null hypothesis")
else:
    print("Fail to reject null hypothesis")

Fail to reject null hypothesis

### Exercise : On the hypothermia dataset , check whether the urgent treatment is effective (Consider columns t.1 and t.2)

In [8]:
df = pd.read_csv("../Files/Hypothermia.csv")
df

,case,code,date,time,weight,t.nur,t.or,t.1,t.2,t.3,t.4,t.5,t.6
0,1,98887,12.0,20.30,2550,29,28,34.0,35.1,,,,
1,2,98528,11.0,18.10,1200,29,23,29.0,33.0,36.5,36.8,,
2,3,95723,3.0,10.24,2650,31,32,31.0,36.8,,,,
3,4,97694,8.0,0.30,800,27,22,32.0,34.0,35,35.5,36,36.5
4,5,96892,6.0,6.20,1880,30,30,32.2,36.6,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,200,,6.0,12.00,2100,29,28,35.9,36.8,,,,
196,201,96464,5.0,7.30,2300,31,30,35.9,36.8,,,,
197,202,98375,11.0,9.05,2500,28,25,35.9,36.0,36.8,,,
198,203,96540,5.0,4.30,3000,32,28,35.9,36.5,36.9,,,
199,204,95486,2.0,12.20,3150,28,27,35.9,36.9,0,,,

In [16]:
usage_data = df[["t.1","t.2"]]
usage_data = usage_data.sample(n=30)

In [17]:
tstat, pval = stats.ttest_rel(usage_data["t.1"],usage_data["t.2"])
print(f"tstat : {tstat}")
print(f"pval : {pval}")

tstat : -14.030019332588648
pval : 1.8595932090795777e-14

In [18]:
alpha = 0.05
if pval < alpha:
    print(f"Reject null hypothesis")
else:
    print("Fail to reject null hypothesis")

Reject null hypothesis