# KNN
- BreastCancer.csv

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier

In [2]:
bcancer = pd.read_csv("BreastCancer.csv")
bcancer.head()

,Code,Clump,UniCell_Size,Uni_CellShape,MargAdh,SEpith,BareN,BChromatin,NoemN,Mitoses,Class
0,61634,5,4,3,1,2,2,2,3,1,Benign
1,63375,9,1,2,6,4,10,7,7,2,Malignant
2,76389,10,4,7,2,2,8,6,1,1,Malignant
3,95719,6,10,10,10,8,10,7,10,7,Malignant
4,128059,1,1,1,1,2,5,5,1,1,Benign

In [9]:
bcancer["Class"].unique()

array(['Benign', 'Malignant'], dtype=object)

In [4]:
bcancer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Code           699 non-null    int64
 1   Clump          699 non-null    int64
 2   UniCell_Size   699 non-null    int64
 3   Uni_CellShape  699 non-null    int64
 4   MargAdh        699 non-null    int64
 5   SEpith         699 non-null    int64
 6   BareN          699 non-null    int64
 7   BChromatin     699 non-null    int64
 8   NoemN          699 non-null    int64
 9   Mitoses        699 non-null    int64
 10  Class          699 non-null    object
dtypes: int64(10), object(1)
memory usage: 60.2+ KB

In [5]:
X, y = bcancer.drop("Class", axis=1), bcancer["Class"]
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=26,test_size=0.3)

In [6]:
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
accuracy_score(y_test,y_pred)

0.5761904761904761

In [7]:
knn = KNeighborsClassifier(n_neighbors=2)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
accuracy_score(y_test,y_pred)

0.6142857142857143

In [13]:
ks = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
scores = []
for k in ks:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    y_pred = knn.predict(X_test)
    scores.append([k,accuracy_score(y_test,y_pred)])
df_scores = pd.DataFrame(scores, columns=["K","Score"])
df_scores.sort_values("Score",ascending=False)

     K     Score
10  11  0.619048
11  12  0.619048
1    2  0.614286
9   10  0.609524
8    9  0.604762
12  13  0.604762
7    8  0.600000
3    4  0.595238
13  14  0.595238
14  15  0.595238
6    7  0.590476
4    5  0.585714
5    6  0.585714
0    1  0.576190
2    3  0.557143