In [19]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, r2_score
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.compose import make_column_selector,make_column_transformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

In [20]:
df = pd.read_csv("../Datasets/Housing.csv")
df

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,61000.0,6360,2,1,1,yes,no,no,no,no,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...
541,91500.0,4800,3,2,4,yes,yes,no,no,yes,0,no
542,94000.0,6000,3,2,4,yes,no,no,no,yes,0,no
543,103000.0,6000,3,2,4,yes,yes,no,no,yes,1,no
544,105000.0,6000,3,2,2,yes,yes,no,no,yes,1,no
545,105000.0,6000,3,1,2,yes,no,no,no,yes,1,no

In [21]:
X, y = df.drop("price",axis=1), df["price"]

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=26,test_size=0.3)

In [23]:
df.isna().sum()

price       0
lotsize     0
bedrooms    0
bathrms     0
stories     0
driveway    0
recroom     0
fullbase    0
gashw       0
airco       0
garagepl    0
prefarea    0
dtype: int64

In [24]:
ohc = OneHotEncoder(sparse_output=False, drop="first").set_output(transform="pandas")
ct_ohe = make_column_transformer((ohc,make_column_selector(dtype_include=object)),
                                 ("passthrough", make_column_selector(dtype_include=['int64','float64'])),
                                 verbose_feature_names_out=False)
ct_ohe = ct_ohe.set_output(transform='pandas')

In [1]:
scaler = StandardScaler().set_output(transform='pandas')
ks = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
scores = []
for k in ks:
    knn = KNeighborsRegressor(n_neighbors=k)
    pipe = Pipeline([("ct_ohe",ct_ohe),("Scaler",scaler),("knn",knn)])
    pipe.fit(X_train,y_train)
    y_pred = pipe.predict(X_test)
    scores.append([k,r2_score(y_test,y_pred)])
df_scores = pd.DataFrame(scores, columns=["K","Score"])
df_scores.sort_values("Score",ascending=False)

NameError: name 'StandardScaler' is not defined

In [34]:
scaler = MinMaxScaler().set_output(transform='pandas')
ks = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
scores = []
for k in ks:
    knn = KNeighborsRegressor(n_neighbors=k)
    pipe = Pipeline([("ct_ohe",ct_ohe),("Scaler",scaler),("knn",knn)])
    pipe.fit(X_train,y_train)
    y_pred = pipe.predict(X_test)
    scores.append([k,r2_score(y_test,y_pred)])
df_scores = pd.DataFrame(scores, columns=["K","Score"])
df_scores.sort_values("Score",ascending=False)

     K     Score
3    4  0.648484
5    6  0.634816
4    5  0.629438
2    3  0.617526
6    7  0.615586
8    9  0.613230
7    8  0.609255
9   10  0.609119
10  11  0.600157
14  15  0.587456
11  12  0.586856
13  14  0.580209
12  13  0.577529
1    2  0.525986
0    1  0.332474