In [4]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, r2_score
from sklearn.preprocessing import StandardScaler, MinMaxScaler,OneHotEncoder
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.compose import make_column_selector,make_column_transformer
from sklearn.preprocessing import OneHotEncoder,LabelEncoder,OrdinalEncoder
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.naive_bayes import BernoulliNB, GaussianNB

In [5]:
df = pd.read_csv("student_dataset_10000_rows.csv")
df.head()

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed

In [7]:
df.isnull().sum().sum()

0

In [8]:
X,y = df.drop("placement_status",axis=1),df["placement_status"]

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=26,test_size=0.3)

# KNN

In [21]:
scaler = StandardScaler().set_output(transform='pandas')
ks = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
scores = []

for k in ks:
    knn = KNeighborsClassifier(n_neighbors=k)  # Changed to Classifier
    pipe = Pipeline([("Scaler", scaler), ("knn", knn)])
    pipe.fit(X_train, y_train)
    y_pred = pipe.predict(X_test)
    scores.append([k, accuracy_score(y_test, y_pred)])

df_scores = pd.DataFrame(scores, columns=["K", "Score"])
df_scores.sort_values("Score", ascending=False)

     K     Score
9   10  0.976333
7    8  0.975333
6    7  0.975000
13  14  0.974667
8    9  0.974000
11  12  0.974000
12  13  0.973333
14  15  0.973333
10  11  0.973000
5    6  0.972667
4    5  0.970667
3    4  0.969000
2    3  0.967000
1    2  0.959333
0    1  0.958667

In [22]:
nb = GaussianNB()
scaler = StandardScaler().set_output(transform="pandas")
pipe = Pipeline([("scaler",scaler),("NB",nb)])
pipe.fit(X_train,y_train)
y_pred = pipe.predict(X_test)
accuracy_score(y_test,y_pred)

0.971